package util

const (
	OAUTH_CLIENT_ID          = "client_id"
	OAUTH_CLIENT_SECRET      = "client_secret"
	OAUTH_USERNAME           = "username"
	OAUTH_PASSWORD           = "password"
	OAUTH_SCOPE              = "scope"
	OAUTH_STATE              = "state"
	OAUTH_GRANT_TYPE         = "grant_type"
	OAUTH_HEADER_NAME        = "Bearer"
	OAUTH_ACCESS_TOKEN       = "access_token"
	OAUTH_EXPIRES_IN         = "expires_in"
	OAUTH_REVOKE_TOKEN       = "token"
	OAUTH_REFRESH_TOKEN      = "refresh_token"
	OAUTH_TOKEN_TYPE         = "token_type"
	OAUTH_TOKEN              = "oauth_token"
	OAUTH_BEARER_TOKEN       = "access_token"
	OAUTH_CLIENT_CREDENTIALS = "client_credentials"
	AUTHORIZATION            = "Authorization"
	OAUTH_RESPONSE_TYPE      = "response_type"
	OAUTH_REDIRECT_URI       = "redirect_uri"
	OAUTH_AUTHORIZATION_CODE = "authorization_code"
	OAUTH_CODE               = "code"
)
